const router = require('express').Router()
const webCemAuth = require('../../middleware/webCemAuth')
const { getDecedentDetails, personContacts, getContractInformation, getContractInformationByContractNumber, getContractInformationByProperty, getContractsByPurchaser, updatePropertyRights, propertySaveSyncEvent, updatePropertyStatus, updateDecedentDetails, updateOwnerDetails } = require('./webCemApis')
const { getCallerDetails, createCall, getLocationOptions, getDecedents, getDecedentList } = require('./webCemCallApis')
const { getContractsForDecedents, createOrUpdateContract, getSaleTypeIds, createAddendum, fetchEhtnicity } = require('./webCemContractApis')
router.use(webCemAuth)
router.get('/decedents/:onePortalId', getDecedentDetails)
router.put('/decedents/:onePortalId', updateDecedentDetails)
router.put('/owners/:onePortalId', updateOwnerDetails)
router.get('/persons/:onePortalId/contacts', personContacts)
router.get('/property/:lot_sell_unit_id/contracts', getContractInformation)
router.get('/contracts/:contract_number', getContractInformationByContractNumber)
router.get('/property/contract-list/:lot_sell_unit_id', getContractInformationByProperty)
router.get('/purchasers/:onePortalId/contracts', getContractsByPurchaser)
router.put('/property/:lot_sell_unit_id', updatePropertyRights)
router.post('/property-sync/:lot_sell_unit_id', propertySaveSyncEvent)
router.post('/property/status-change/:lot_sell_unit_id', updatePropertyStatus)
router.get('/get-caller-details', getCallerDetails)
router.post('/create-call', createCall)
router.get('/call/location-options', getLocationOptions)
router.get('/call/get-decedents/:reasonId/:callId', getDecedents)
router.get('/call/get-decedents', getDecedentList)
router.get('/contract/:onePortalId', getContractsForDecedents)
router.post('/contract/create-contract', createOrUpdateContract)
router.get('/contract/dropdown-values/:onePortalId/:needType', getSaleTypeIds)
router.get('/getEthnicity', fetchEhtnicity)
router.post('/contract/create-addendum', createAddendum)
module.exports = router
