const router = require('express').Router()
const loginValidation = require('../lib/validations').login

// Handlers initialization
const signInHandler = require('./LogIn/login')
const callsHandler = require('./Calls')
const usersHanlder = require('./users')
const casesHandler = require('./cases')
const personHandler = require('./person')
const placeHandler = require('./addressPlace')
const ticketsHandler = require('./Tickets')
const funeralHandler = require('./funeral/index')
const arrangementHandler = require('./arrangement')
const employeesHandler = require('./employees/index')
const discountsHandler = require('./discounts')
const certifierHandler = require('./certifiers')
const policyHandler = require('./LogIn/policy')
const authentication = require('../middleware/authentication')
const agreementItemHandler = require('./agreementItem')
const paymentsHandler = require('./payments')
const formsHandler = require('./forms')
const itemTypesHandler = require('./itemTypes')
const itemHandler = require('./item')
const propertiesHandler = require('./properties')
const packagesHandler = require('./packages')
const schedulingHandler = require('./scheduling')
const fileUploadHandler = require('./uploadFile')
const faaHandler = require('./familyPortal')
const notesHandler = require('./notes')
const adjustmentsHandler = require('./adjustments')
const financeOptionHandler = require('./financeOption')
const vendorHandler = require('./vendor')
const { fetchRoles } = require('./person/contacts/contactHandler')
const vehiclesHandler = require('./vehicles/index')
const crematoryRetortsHandler = require('./crematoryRetorts/index')
const workOrderHandler = require('./workOrders/index')
const chapelHandler = require('./chapel')
const daySheetHandler = require('./daySheets')
const purchaseOrderHandler = require('./purchaseOrders/index')
const { userRolesHandler } = require('./LogIn/userRoles')
const approvalHandler = require('./approvals')
const miscSalesHandler = require('./miscSales')
const adminHandler = require('./admin')
const hmisHandler = require('./hmis')
const wholesaleCremationHandler = require('./wholesaleCremation')
const webCemHandler = require('./webCem')
const dashboardHandler = require('./dashboard')
const onePageDaySheetHandler = require('./onePageDaySheets')
const quotationHandler = require('./quotation')
const urnTransferHandler = require('./urnTransfer')

const { upSyncPayments, downSyncPayments } = require('../appQueues/hmisSyncWorker')
const { generateRecipientUrlAndDocusign } = require('./forms/formsHandler')
const { createGAInsurance } = require('./gaInsurance/gaInsurance')
// GA insurance
router.get('/ga-insurance', createGAInsurance)

router.get('/docusignlink/:recipientId', generateRecipientUrlAndDocusign)
router.get('/contact/roles', fetchRoles)
router.use('/login', loginValidation, signInHandler)
router.use('/calls', callsHandler)
router.use('/users', usersHanlder)
router.use('/cases', casesHandler)
router.use('/organization', placeHandler)
router.use('/person', personHandler)
router.use('/adjustments', adjustmentsHandler)
router.use('/approvals', approvalHandler)
// TODO: below route is not used any where
router.use('/funeral', funeralHandler)
router.use('/tickets', ticketsHandler)
router.use('/arrangement', arrangementHandler)
router.use('/employees', employeesHandler)
router.use('/discounts', discountsHandler)
router.use('/certifiers', certifierHandler)
router.use('/agreement', agreementItemHandler)
router.use('/payments', paymentsHandler)
router.use('/forms', formsHandler)
router.use('/finance-options', financeOptionHandler)

router.use('/itemTypes', itemTypesHandler)

router.use('/properties', propertiesHandler)
router.use('/scheduling', schedulingHandler)
router.use('/chapel', chapelHandler)
router.use('/day-sheets', daySheetHandler)
router.use('/one-page-day-sheets', onePageDaySheetHandler)
router.use(authentication)
router.use('/getPolicies', policyHandler)
router.use('/userRoles', userRolesHandler)
router.use('/faa', faaHandler)
router.use('/webcem', webCemHandler)

// Refactored routers
router.use('/items', itemHandler)
router.use('/packages', packagesHandler)
router.use('/notes', notesHandler)
router.use('/uploadFile', fileUploadHandler)
router.use('/vendor', vendorHandler)
router.use('/vehicles', vehiclesHandler)
router.use('/crematory-retorts', crematoryRetortsHandler)
router.use('/work-order', workOrderHandler)
router.use('/purchase-order', purchaseOrderHandler)
router.use('/urn-transfer', urnTransferHandler)
router.use('/miscSales', miscSalesHandler)
router.use('/admin', adminHandler)
router.use('/hmis', hmisHandler)
router.use('/wholesale-cremation', wholesaleCremationHandler)
router.use('/dashboard', dashboardHandler)
router.use('/quotation', quotationHandler)

// sync job routes
router.get('/up-sync-job', upSyncPayments)
router.get('/down-sync-job', downSyncPayments)

module.exports = exports = router
