const router = require('express').Router()

const authentication = require('../../middleware/authentication')
const sendInviteHandler = require('./sendInvite')
const decedantListHandler = require('./getDecedantforAdvisor')
const { decedentInfoHandler, getDecedentDetails } = require('./getDecedentDetails')
const familyAdvisorHandler = require('./getFamilyAdvisor')
const submitFAAHandler = require('./submitFromFAA')
const saveServiceHandler = require('./saveInterestedService')
const getServiceHandler = require('./getInterestedServices')
const lockDecedent = require('./lockDecedent')
const unlockDecedent = require('./unlockDecedent')
const getPrayerCard = require('./getPrayerCard')
const savePrayerCard = require('./savePrayerCard')
const lockPrayerCard = require('./lockPrayerCard')
const unlockPrayerCard = require('./unlockPrayerCard')
const getProgram = require('./getProgram')
const saveProgram = require('./saveProgram')
const lockProgram = require('./lockProgram')
const unlockProgram = require('./unlockProgram')
const getCardsStatus = require('./getCardsStatus')
const { getObituary, saveOrEditObituary, getObituaryStatus } = require('./obituary')
const lockObituary = require('./lockObituary')
const unlockObituary = require('./unlockObituary')
const edrsAutoLock = require('./edrsAutoLock')

const interestedServiceValidation = require('../../lib/validations').interestedService
const obituaryValidation = require('../../lib/validations').obituary

router.use(authentication)
router.post('/:onePortalId/invite', sendInviteHandler)
router.get('/:advisor/decedent', decedantListHandler)
router.get('/:onePortalId/advisor', familyAdvisorHandler)
router.get('/:decedentId/decedent-info', decedentInfoHandler)
router.post('/:decedentId/pull', submitFAAHandler)
router.post('/:decedentId/services', interestedServiceValidation, saveServiceHandler)
router.get('/:onePortalId/services', getServiceHandler)
router.post('/:decedentId/lock', lockDecedent)
router.post('/:decedentId/unlock', unlockDecedent)
router.get('/:onePortalId/prayer-card', getPrayerCard)
router.post('/:decedentId/prayer-card', savePrayerCard)
router.post('/:decedentId/prayer-card/lock', lockPrayerCard)
router.post('/:decedentId/prayer-card/unlock', unlockPrayerCard)
router.get('/:onePortalId/program', getProgram)
router.post('/:decedentId/program', saveProgram)
router.post('/:decedentId/program/lock', lockProgram)
router.post('/:decedentId/program/unlock', unlockProgram)
router.get('/:onePortalId/cards-status', getCardsStatus)
router.get('/:opi/obituary', getObituary)
router.post('/:opi/obituary', obituaryValidation, saveOrEditObituary)
router.get('/:decedentId/obituary-status', getObituaryStatus)
router.post('/:decedentId/obituary/lock', lockObituary)
router.post('/:decedentId/obituary/unlock', unlockObituary)
router.post('/:decedentId/edrs/auto-lock', edrsAutoLock)
router.get('/:onePortalId/decedent-details', getDecedentDetails)

module.exports = exports = router
